### ISSUE TITLE
[IOS] Clicking cancel when using `store.refresh` doesn't trigger a promise-like event

### ISSUE THREAD

**Issue by mcfarljw** [j3k0/cordova-plugin-purchase#1040]
### system info

```
OSX Catalina 10.15.4
Cordova 9.0.0
Device: iPhone iOS 13.5
Plugin Version: 10.2.0
```

### Expected behavior

There is a way to know when a user has cancelled the password dialog trigger when restoring purchases using `store.refresh` and the promise-like callbacks.

### Observed behavior

According to the https://github.com/j3k0/cordova-plugin-purchase/releases/tag/v10.1.2 notes there is a new promise-like callback for finished when refreshing/restoring purchases. It appears that that if the user clicks cancel when prompted for a password it doesn't trigger either finished or completed which makes it hard to hide any progress indicators.

### Steps to reproduce

1. Use account with no owned purchases
1. Use `store.refresh` listening to finished and complete
1. Click cancel when prompted for a password

**Comment by j3k0** [comment]
PR #1042 should fix this (extends the callback with new events, ensures `finished` is always called. Would you mind testing it? Thanks

**Comment by mcfarljw** [comment]
Thanks for the quick patch! I will test the PR tomorrow and let you know how it went.

**Comment by mcfarljw** [comment]
I just did a test pulling the plugin from https://github.com/j3k0/cordova-plugin-purchase.git#94cd5f7c2294bd63428ba57a77860fae1b05bb00 and it doesn't appear that failed or cancelled are firing. Here is a snippet of what I'm using:

```js
store.refresh()
          .failed(() => {
            alert('refresh failed')
            resolve()
          })
          .cancelled(() => {
            alert('refresh cancelled')
            resolve()
          })
          .finished(() => {
            alert('refresh finished')
            resolve()
          })
```

After calling `store.refresh()` I still get the popup for my password, if I tap cancel none of them appear to fire an alert.

**Comment by j3k0** [comment]
Ok. Might not work as hoped. I implemented according to apple docs but had no way to test cancellation. Careful with alerts though, they do not work for code running from callbacks triggered from native code (which is probably the case here) you might want to double check with console logs.

**Comment by j3k0** [comment]
... also related to your code. notice that `failed` and `cancelled` will also call `finished`.

**Comment by mcfarljw** [comment]
My original code wasn't using alerts but rather disabling a page full page overlay with loading spinner. It still doesn't seem to finish though. When I get a chance I can try debugging through some of the code in the plugin to see what is and isn't triggering.

**Comment by j3k0** [comment]
I can't reproduce, it works on iOS and OSX in my test app.

**Comment by j3k0** [comment]
(PR merged into master)
