### ISSUE TITLE
Errors when app is started offline

### ISSUE THREAD

**Issue by francoisduchemin** [j3k0/cordova-plugin-purchase#863]
My ionic app is displaying some IAP initialization errors when it is started without any internet connection. I read in the documentation that I have to install the plugin `cordova-plugin-network-information`.
Do I have to configure it in a specific way?

I am planning to call the IAP initialization code only if the network is connected:
```
this.connected = this.network.onConnect().subscribe(data => {
    // if IAP not initialized yet, init IAP
}, error => console.error(error));
```

Do you think it's ok to do it like this? Do you have better ideas?

**Comment by j3k0** [comment]
Can you show me what the errors are? They might be just normal things.

As mentioned in the doc, the plugin requires internet connection in order to work (since it involves communicating with Apple/Google/Microsoft servers). When initialization fails the plugin will retry (in a smart way) until it can proceed, so you might not need this extra piece of code.

Initialization also performs a bunch of "non-online" operations, so you might be better keeping the initialization as soon as possible (or I do not guarantee the side effects)... Apple (in particular) requires the StoreKit handlers to be setup as soon as possible (regardless of the status of the internet connection).

**Comment by francoisduchemin** [comment]
Thanks for your answer.

So you mean I just have to install `cordova-plugin-network-information` and that's it? No specific configuration?

The errors I get are "my" own errors, there's nothing wrong with `cordova-plugin-purchase`.
Basically when the app is started I initialize the IAP as soon as possible by registering handlers and then calling `store.refresh()`.

Two of the registered handlers are `productError` and `storeError`:
```
this.store.when(this.productId).error(this.productError);
this.store.error(this.storeError);
```
These 2 handlers display alerts.

When `store.refresh()` is called and the phone is offline, these 2 handlers are called so error messages are displayed to the user.

I changed my implementation to initialize the `cordova-plugin-purchase` (i.e. register handlers and call `store.refresh()` only when the phone is online). Do you think I should initialize it even if the phone is offline, and just stop showing error messages in these 2 handlers instead?

**Comment by j3k0** [comment]
Yes, I think you should initialize even when the phone is offline.

An easy step could be to filter out the errors you don't want to display in `this.storeError()`. Errors have an error code (see the API documentation for a list), initialization error or communication errors shouldn't be displayed to the user -- especially if it's not the result of a call to `store.order()`.

**Comment by francoisduchemin** [comment]
Ok thanks for your feedback! I will do it like this.

But if I understand correctly, `cordova-plugin-network-information` is still needed to perform the initialization-retry in a smart way, is this correct?

**Comment by j3k0** [comment]
Yes, as per the documentation:

> Sometimes, the plugin cannot connect to the app store because it has no network connection. It will then retry either:
>
> - periodically after a certain amount of time;
> - when the device fires an 'online' event.
>
> The cordova-plugin-network-information plugin is required in order for the 'online' event to be properly received in the Cordova application. Without it, this plugin will only be able to use the periodic check to determine if the device is back online.

Without `cordova-plugin-network-information`, the plugin will retry after a few seconds, then double the delay, and do it again and again (up to a 2 minutes delay if I recall correctly)

**Comment by francoisduchemin** [comment]
Ok thanks a lot!
I guess you can close the issue.

**Comment by j3k0** [comment]
Let me know if you think there's another place in the documentation where this should be mentioned ;-) I don't have a fresh eye on it to realize those things.

**Comment by francoisduchemin** [comment]
sorry to reopen the issue! I tested the process and it is working perfectly on iOS: I start the app while the device is offline, the IAP plugin is initialized (it sends store and product errors as expected), then I turn on the wifi and all handlers are automatically called.

On Android with the same code base, it looks like the retry mechanism is not working correctly. When I turn on the wifi, the handlers are not called... even if I wait several minutes. And I don't see anything in the logs... I'm not sure if I'm doing something wrong.

**Comment by j3k0** [comment]
Correct, this wasn't implemented for Android. I've just pushed a fix for this in the master branch. 680e863

**Comment by rafaellop** [comment]
Unfortunately this still doesn't work on Android. If you leave an app and the store offline until the initial several attempts it tries several times then fires `store.error` with `{code: 6777017, message: "Transaction verification failed: "}` with the debug log as `DEBUG: validation failed, no retrying, trigger an error`. If you switch the device to be online the network information plugin fires the `"online"` event ( I can catch it on my own), but it is not caught by the `store-android.js` and the store stays uninitiated even if the app is online.

Is there a way to retry the init with some API call? I tried to use the `refresh()` method but on iOS it gives issues with the login popup which I'd like to avoid.
