### ISSUE TITLE
[Android] - Attempt to invoke interface method 'int java.util.List.size()' on a null object reference

### ISSUE THREAD

**Issue by JumBay** [j3k0/cordova-plugin-purchase#948]
### system info

```
OSX Sierra 10.15 
Cordova 9.0.0 (cordova-lib@9.0.1) - cordova-android 8.1.0
Device: Galaxy Note10+ Android 9
Plugin Version: cordova-plugin-purchase@9.0.0
```
For my app (android version) I get this error that appears in Crashlytics: 
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
       at cc.fovea.PurchasePlugin.lambda$queryPurchases$1(PurchasePlugin.java:296)
       at cc.fovea.-$$Lambda$PurchasePlugin$ERhMchr2fWN0IfG8YEXLUlz_LzM.run(:2)
       at cc.fovea.PurchasePlugin.executeServiceRequest(PurchasePlugin.java:849)
       at cc.fovea.PurchasePlugin.queryPurchases(PurchasePlugin.java:282)
       at cc.fovea.PurchasePlugin.onStart(PurchasePlugin.java:681)
       at org.apache.cordova.PluginManager.onStart(PluginManager.java:275)
       at org.apache.cordova.CordovaWebViewImpl.handleStart(CordovaWebViewImpl.java:466)
       at org.apache.cordova.CordovaActivity.onStart(CordovaActivity.java:305)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1395)
       at android.app.Activity.performStart(Activity.java:7374)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3187)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7263)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

I thought it will be useful for you to be aware of.

Thanks for your work

**Comment by j3k0** [comment]
Thanks for the report. Fixed in branch `v9` and `master`

**Comment by rafaellop** [comment]
I'm still getting the error in the Play Console using the master branch.

```
java.lang.NullPointerException: 
  at cc.fovea.PurchasePlugin.lambda$queryPurchases$1 (PurchasePlugin.java:296)
  at cc.fovea.-$$Lambda$PurchasePlugin$ERhMchr2fWN0IfG8YEXLUlz_LzM.run (Unknown Source:2)
  at cc.fovea.PurchasePlugin.executeServiceRequest (PurchasePlugin.java:849)
  at cc.fovea.PurchasePlugin.queryPurchases (PurchasePlugin.java:282)
  at cc.fovea.PurchasePlugin.onStart (PurchasePlugin.java:681)
  at org.apache.cordova.PluginManager.onStart (PluginManager.java:275)
  at org.apache.cordova.CordovaWebViewImpl.handleStart (CordovaWebViewImpl.java:466)
  at org.apache.cordova.CordovaActivity.onStart (CordovaActivity.java:305)
  at android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1395)
  at android.app.Activity.performStart (Activity.java:7348)
  at android.app.ActivityThread.handleStartActivity (ActivityThread.java:3145)
  at android.app.servertransaction.TransactionExecutor.performLifecycleSequence (TransactionExecutor.java:180)
  at android.app.servertransaction.TransactionExecutor.cycleToPath (TransactionExecutor.java:165)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:142)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:70)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1955)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7076)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)
```
